version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  expenses-api:
    build: .
    container_name: expenses-service
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=ExpensesDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True"
    ports:
      - "5117:80"

volumes:
  sqlserver_data:
